### ISSUE TITLE
To remove hard coded app name

### ISSUE THREAD

**Issue by helio-frota** [obs-nebula/frontend-react#12]
https://github.com/obs-nebula/frontend-react/blob/2f5b90de0e5587f9b616d6eb2e89fb9805a4ed76/front-end/src/tracing.js#L20

We can use this instead: https://github.com/obs-nebula/check-traces/blob/main/tracing.js#L10

**Comment by pnaik1** [comment]
Hello @helio-frota I was trying to do that comparing the check-traces example , but I notice that I getting this
![jaeger123](https://user-images.githubusercontent.com/99238909/210337567-5f45fca8-8521-4d89-b91b-012c646dc464.png)
may be i think it dont work in react application
