### ISSUE TITLE
Deploy to OpenShift with otelcol and jaeger operators

### ISSUE THREAD

**Issue by helio-frota** [obs-nebula/frontend-react#6]
~~For this we can to use a branch for example `deploy`, with that we can keep the `main` branch as simple as possible.~~

**Comment by helio-frota** [comment]
@pnaik1 in case you finish this first please add a comment here :+1:

**Comment by helio-frota** [comment]
@pnaik1 let's use the main branch and avoid that `deploy`, wdyt?

**Comment by pnaik1** [comment]
okay @helio-frota , yeah it will be better

**Comment by helio-frota** [comment]
> let's use the main branch and avoid that deploy, wdyt?

My previous comment from 2 weeks ago probably related to the odo+devfile situation, trying to minimize any extra efforts. But in fact we are going with the deploy branch. I already added some modifications there related to the express-server deployment.

**Comment by helio-frota** [comment]
I'm going to close this issue here.
* We can deploy both front-end and back-end already using `oc` command.
* This was created more than 1 month ago `Dec 7, 2022` and we changed our strategy.
* The full description is missing as we moved forward doing other things.
* The remaining part is related to the Tech Preview otelcol that needs to be updated to the latest version of upstream.
